[project]
name = "vvl1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "firebase-admin>=6.8.0",
    "icecream>=2.1.4",
    "jinja2>=3.1.6",
    "uvicorn>=0.34.2",
]
